---
version: "3.7"
# ---------------------------------------------------------------------
# | NodeJS Service                                                    |
# ---------------------------------------------------------------------

services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: paulserbandev/api-server
    container_name: api-server-compose
    restart: always
    volumes: 
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT
