---
version: "3.7"
# ---------------------------------------------------------------------
# | NodeJS Service                                                    |
# ---------------------------------------------------------------------

services:
  express-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: paulserbandev/express-api-server
    container_name: express-api-server-compose
    restart: always
    volumes: 
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - $NODE_PORT:$NODE_DOCKER_PORT
